services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    user: ${USER}
#    volumes:
#     - ./:/var/www
    depends_on:
      - mysql
    ports:
      - "${APP_PORT:-8765}:8000"

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${MYSQL_FORWARD_PORT:-3310}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
